substitutions:
  device_name: esp32general
  friendly_name: esp32general
  esp32_board: esp32dev
  esp32_variant: esp32
  relay_pin:
    number: GPIO23
    inverted: true
  led_pin: GPIO5
  button_pin: GPIO19
  #sel_pin: GPIO14
  #cf_pin: GPIO27
  #cf1_pin: GPIO26
  #voltage_divider: "0"
  #current_resistor: "0"
  #power_multiply: "0"
  localdomain: ".local"
  mqttbroker: "homeassistant.local"  
  ble_pin: !secret esp32general__ble_pin

packages:
  base: !include base-brainplug-esp32.yaml
  #power: !include pwrmeter-brainplug.yaml

api:
  encryption:
    key: !secret esp32general__encryption_key
  reboot_timeout: 0s
