substitutions:
  device_name: goklugeu3s
  friendly_name: goklugeu3s
  board_type: esp01_1m
  relay_pin: GPIO15
  led_pin: GPIO2
  button_pin: GPIO13
  sel_pin: GPIO12
  cf_pin: GPIO5
  cf1_pin: GPIO14
  voltage_divider: "2143"
  current_resistor: "0.001205"
  power_multiply: "1.0"
  mqttbroker: "homeassistant.local"  
  localdomain: ".local"

packages:
  base: !include base-brainplug.yaml
  power: !include pwrmeter-brainplug.yaml

api:
  encryption:
    key: !secret goklugeu3s__encryption_key
  reboot_timeout: 0s
