substitutions:
  device_name: nousa8t
  friendly_name: nousa8t
  esp32_board: esp32dev
  esp32_variant: esp32
  relay_pin: GPIO13
  led_pin: GPIO02
  button_pin: GPIO04
  sel_pin: GPIO14
  cf_pin: GPIO27
  cf1_pin: GPIO26
  voltage_divider: "1514"
  current_resistor: "0.001271"
  power_multiply: "1.310"
  localdomain: ".local"
  mqttbroker: "homeassistant.local"
  ble_pin: !secret nousa8t__ble_pin

packages:
  base: !include base-brainplug-esp32.yaml
  power: !include pwrmeter-brainplug.yaml

api:
  encryption:
    key: !secret nousa8t__encryption_key
  reboot_timeout: 0s
